blank_issues_enabled: false
contact_links:
  - name: ⚠️ Application issue
    url: https://github.com/bigbabyboost/nekotachi/issues/new/choose
    about: Issues and requests about the app itself should be opened in the nekotachi repository instead
  - name: 🖥️ Nekotachi website
    url: https://nekotachi.app/help/
    about: Guides, troubleshooting, and answers to common questions
